name: daydreams

services:
  chroma:
    image: chromadb/chroma:0.6.3
    restart: always
    ports:
      - "8000:8000"
  mongo:
    image: mongo:8.0.4
    restart: always
    ports:
      - "27017:27017"
